spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyDB
    username: root
    password: happyjeong97

logging:
  level:
    com.security.jwt: debug
    org.mybatis: debug
    org.apache.ibatis: debug

jwt:
  key: "your-very-secret-key-your-very-secret-key"  # 32바이트 이상 문자열
  access-expiration: 1800000  # 만료 시간 (1시간 = 3600000ms)
  refresh-expiration: 1209600000
  issuer: "hohyun"  # 토큰 발급자 정보
  token-prefix: "Bearer "  # Authorization 헤더 접두사